### ISSUE TITLE
wine-wechat 窗口阴影置顶解决方案 - Reverier 个人博客

### ISSUE THREAD

**Issue by Reverier-Xu** [Reverier-Xu/discussions#2]
https://www.wootec.top/2020/02/16/wine-wechat%E9%98%B4%E5%BD%B1%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88/ 

 Ha1cyon-CTF 芜湖 题解源代码先上源代码:

**Comment by szcf-weiya** [comment]
很好用的策略！不过我的阴影窗口的编号不总是 0xXXXX0014，有时是 0xXXXX0015，但是跟“微信”的 id 总是相差 8（虽然这个规律对你好像不太一样），所以我把 25 行改成
```python
shadow = hex(int(id, 16) + 8)
```
