### ISSUE TITLE
Reverier 个人博客

### ISSUE THREAD

**Issue by Reverier-Xu** [Reverier-Xu/discussions#21]
https://www.wootec.top/message/ 

 Woooooooooooooooooooootec

**Comment by Reverier-Xu** [comment]
欢迎师傅们在此随意发言噢!

**Comment by Sumimiao** [comment]
I made it! I am cominnnnnng!!!!!!!

**Comment by Reverier-Xu** [comment]
> @Sumimiao
> I made it! I am cominnnnnng!!!!!!!

啊 这

**Comment by xxy1126** [comment]
你好，可以不可发一下moectf re的wp，感谢！！！

**Comment by Reverier-Xu** [comment]
> @xxy1126
> 你好，可以不可发一下moectf re的wp，感谢！！！

https://blackbird-bb.github.io/2020/10/31/2020moectf-Reverse/

先看这个吧emmmm, 官方的wp我咕咕咕了 (

等有时间写一下

**Comment by xxy1126** [comment]
> @Reverier-Xu
> > @xxy1126
> > 你好，可以不可发一下moectf re的wp，感谢！！！
> 
> https://blackbird-bb.github.io/2020/10/31/2020moectf-Reverse/
> 
> 先看这个吧emmmm, 官方的wp我咕咕咕了 (
> 
> 等有时间写一下

好的，太感谢了！

**Comment by Y7n05h** [comment]
师傅您好，我十分喜欢您博客中的代码高亮的主题，请问您是如何配置代码高亮的方案呢，使用的代码高亮的主题是哪个呢？

**Comment by Reverier-Xu** [comment]
> @Y7n05h
> 师傅您好，我十分喜欢您博客中的代码高亮的主题，请问您是如何配置代码高亮的方案呢，使用的代码高亮的主题是哪个呢？

`highlightJS`里内置的`atom-one-dark`主题：[Highlight JS Themes](https://github.com/highlightjs/highlight.js/tree/master/src/styles)

**Comment by Y7n05h** [comment]
> > @Y7n05h
> > 师傅您好，我十分喜欢您博客中的代码高亮的主题，请问您是如何配置代码高亮的方案呢，使用的代码高亮的主题是哪个呢？
> 
> `highlightJS`里内置的`atom-one-dark`主题：[Highlight JS Themes](https://github.com/highlightjs/highlight.js/tree/master/src/styles)

感谢回复

**Comment by Hancl777** [comment]
踩踩

**Comment by Hancl777** [comment]
跑跑蹦蹦跳跳

**Comment by Laifang** [comment]
您好大佬，我对您两年前开发的ISAE 和ICTFE 项目很感兴趣，但是无论是c++版本和python版本 我都没有构建或者运行成功，能提供一下您成功运行的环境吗，万分感谢！ lfs451@qq.com

**Comment by Reverier-Xu** [comment]
已答复至预留邮箱

________________________________
发件人: desire sunmer ***@***.***>
发送时间: Thursday, May 12, 2022 5:22:03 AM
收件人: Reverier-Xu/blog_comment ***@***.***>
抄送: Reverier ***@***.***>; Mention ***@***.***>
主题: Re: [Reverier-Xu/blog_comment] Reverier 个人博客 (#21)


您好大佬，我对您两年前开发的ISAE 和ICTFE 项目很感兴趣，但是无论是c++版本和python版本 我都没有构建或者运行成功，能提供一下您成功运行的环境吗，万分感谢！ ***@***.******@***.***>

―
