### ISSUE TITLE
POST - Reverier's Blog

### ISSUE THREAD

**Issue by Reverier-Xu** [Reverier-Xu/discussions#52]
https://www.wootec.top/2020/08/07/POST/ 

 如题

**Comment by ll1ng** [comment]
怎么会有宁这么贴心的人:speak_no_evil:tql！男默女泪

**Comment by Reverier-Xu** [comment]
> @ll1ng
> 怎么会有宁这么贴心的人:speak_no_evil:tql！男默女泪

啊这

不至于不至于... 我当初百度了两个月也没搜到怎么POST... 可能太简单了导致没人想写这个, 于是就写一下得了.

**Comment by ksf1464** [comment]
rx,yyds!网上找了半天没搞懂，现在终于会post了
