### ISSUE TITLE
播放器... - Reverier's Blog

### ISSUE THREAD

**Issue by Reverier-Xu** [Reverier-Xu/discussions#62]
https://www.wootec.top/2020/11/12/2020-11-12-%E6%92%AD%E6%94%BE%E5%99%A8/ 

 Woooooooooooooooooooootec

**Comment by Reverier-Xu** [comment]
**为什么要用MuseDash做预览图片:** 没找着好用的测试用例, 就随手拖了一个, 请勿在意

**Comment by orangecheers-x** [comment]
我想用
