### ISSUE TITLE
朋友们

### ISSUE THREAD

**Issue by Reverier-Xu** [Reverier-Xu/discussions#71]
https://blog.woooo.tech/friends/?code=e135e8ddb085fe2abbed

**Comment by Jacka1ope** [comment]
何德何能和上面这些巨佬并排啊QAQ

**Comment by Reverier-Xu** [comment]
> @C3ru1eaN
> 何德何能和上面这些巨佬并排啊QAQ

快去更博客（XD

**Comment by snowolf46** [comment]
突然才发现你搬家了

**Comment by Reverier-Xu** [comment]
> @snowolf46
> 突然才发现你搬家了

应该是去年换的

**Comment by arttnba3** [comment]
👴来膜全能の神RX大哥了

**Comment by Reverier-Xu** [comment]
> @arttnba3
> 👴来膜全能の神RX大哥了

❓

**Comment by dmlgzs** [comment]
膜拜 RX 神

**Comment by 66RING** [comment]
膜拜 RX 神 or2

**Comment by arttnba3** [comment]
踩踩
